import Head from 'next/head'

import { ThemeProvider } from '@mui/material/styles'
import '@/styles/globals.css'
import CssBaseline from '@mui/material/CssBaseline'

import { DefaultSeo } from 'next-seo'
import { SeoConfig } from '@/data/SeoConfig'

import theme from '@/styles/theme'
import AppLayout from '@/layouts/AppLayout'

export default function App({ Component, pageProps }) {
  return (
    <ThemeProvider theme={theme}>
      <DefaultSeo {...SeoConfig} />
      <CssBaseline />
      <Head>
        <title>Josenaldo de Oliveira Matos Filho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Component {...pageProps} />
    </ThemeProvider>
  )
}
