import { Button } from '@mui/material'
import Grid from '@mui/material/Unstable_Grid2/Grid2'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Josenaldo de Oliveira Matos Filho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Josenaldo Matos</h1>
        <Grid container spacing={2}>
          <Grid>
            <Button variant="contained" color="primary">
              Primário
            </Button>
          </Grid>
          <Grid>
            <Button variant="contained" color="secondary">
              Secundário
            </Button>
          </Grid>

          <Grid>
            <Button variant="contained" color="success">
              Sucesso
            </Button>
          </Grid>

          <Grid>
            <Button variant="contained" color="error">
              Erro
            </Button>
          </Grid>

          <Grid>
            <Button variant="contained" color="warning">
              Aviso
            </Button>
          </Grid>

          <Grid>
            <Button variant="contained" color="info">
              Informação
            </Button>
          </Grid>
        </Grid>
      </div>
    </>
  )
}
