import { Button } from '@mui/material'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Josenaldo de Oliveira Matos Filho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Josenaldo Matos</h1>
        <div container spacing={2}>
          <Button variant="contained" color="primary">
            Primário
          </Button>

          <Button variant="contained" color="secondary">
            Secundário
          </Button>

          <Button variant="contained" color="success">
            Sucesso
          </Button>

          <Button variant="contained" color="error">
            Erro
          </Button>

          <Button variant="contained" color="warning">
            Aviso
          </Button>

          <Button variant="contained" color="info">
            Informação
          </Button>
        </div>
      </div>
    </>
  )
}
